### ISSUE TITLE
Request: Please don't abandon this

### ISSUE THREAD

**Issue by spiritualgeek** [alexobenauer/obsidian-tag-navigator#13]
Please continue and get this through to process :)

**Comment by miguelmarcos** [comment]
> Please continue and get this through to process :)

I agree. Maybe in the worst case, another Obsidian developer can just keep it compatible. It would be beneficial to get it listed officially, too. This would be a plus in getting more people in the community working with this concept and giving feedback on it. Thanks in any case, Alexander.

**Comment by spiritualgeek** [comment]
It's a brilliant idea but even though I have it running I'm uninstalling as there is no indication that it will continue, and I don't want it to become central to my workflow until I know it will continue

**Comment by pcuellar** [comment]
Adding to the choir. I am a regular user of this plugin and would love to see it going forward

**Comment by spiritualgeek** [comment]
no longer using this
